name: Monitor AI Provider API Changes

on:
  # Run every hour
  # schedule:
  #   - cron: '0 * * * *'
  # Allow manual triggering
  workflow_dispatch:
  # Run when the workflow file is changed
  push:
    branches: [main]
    paths:
      - '.github/workflows/check-for-changes.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    strategy:
      matrix:
        source:
          - name: cohere
            openapi_url: "https://raw.githubusercontent.com/cohere-ai/cohere-developer-experience/main/cohere-openapi.yaml"
          - name: mistral
            openapi_url: "https://docs.mistral.ai/redocusaurus/plugin-redoc-0.yaml"
          - name: openai
            openapi_url: "https://app.stainless.com/api/spec/documented/openai/openapi.documented.yml"
          - name: togetherai
            openapi_url: "https://raw.githubusercontent.com/togethercomputer/openapi/refs/heads/main/openapi.yaml"
          # xAI has some bot protection which prevents us from downloading. the spec ...
          # See https://github.com/gr2m/ai-provider-api-changes/pull/20/files for an example
          # - name: xai
          #   openapi_url: "https://docs.x.ai/openapi.json"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create cache directory
        run: mkdir -p cache/${{ matrix.source.name }}

      - name: Download API specification
        id: detect-first-run
        run: |
          # Check if this is the first run (no previous spec exists)
          if [ ! -f "cache/${{ matrix.source.name }}/openapi.yml" ]; then
            echo "first_run=true" >> $GITHUB_OUTPUT
            echo "New specification detected"
            exit 0
          fi

      - name: Download
        id: download
        run: |
          # Download the current OpenAPI API spec
          curl -s "${{ matrix.source.openapi_url }}" -o cache/${{ matrix.source.name }}/openapi.yml

      # If this is the first run, create PR with the initial spec
      - name: Create initial PR
        if: steps.detect-first-run.outputs.first_run == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          title: "feat: add initial ${{ matrix.source.name }} API specification"
          body: |
            The initial ${{ matrix.source.name }} API specification file for monitoring changes.
            
            This repository will now track changes to the ${{ matrix.source.name }} API specification and create automated pull requests when changes are detected.
          branch: update/${{ matrix.source.name }}
          delete-branch: true
          labels: |
            provider:${{ matrix.source.name }}
            version:breaking
          commit-message: "feat: add initial ${{ matrix.source.name }} API specification"

      - name: Detect changes
        if: steps.detect-first-run.outputs.first_run != 'true'
        id: detect-changes
        run: |
          # Compare with previous version using git
          if ! git diff --quiet HEAD cache/${{ matrix.source.name }}/openapi.yml; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
            echo "Changes detected in ${{ matrix.source.name }} API specification"
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      - name: Diff
        if: steps.detect-changes.outputs.changes_detected == 'true'
        id: diff
        run: |
          GIT_DIFF=$(git diff) 
          echo "text<<EOF" >> $GITHUB_OUTPUT
          echo "$GIT_DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Generate release notes
        if: steps.detect-changes.outputs.changes_detected == 'true'
        id: release-notes
        uses: vercel/ai-action@v2
        with:
          model: 'openai/gpt5'
          api-key: ${{ secrets.AI_GATEWAY_API_KEY }}
          prompt: |
            Analyze the following OpenAPI specification diff and calculate these three things

            1. Summary of changes as conventional commit messages (max. 100 characters)
            2. A detailed description of the changes, in markdown format
            3. The type of version change: "breaking", "feature", or "fix"

            For the markdown description, create three sections:

            1. Breaking changes (removed endpoints, parameters, or changed behavior)
            2. New features (new endpoints, parameters, or options)
            3. Fixes (documentation updates, typo corrections)

            If a section has no content, omit it from the release notes.

            Do not list items in new features that are listed in breaking changes.
            Do not list items in fixes that are listed in breaking changes or new features.

            Diff:
            ${{ steps.diff.outputs.text }}
          schema: |
            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "title": "Change Description",
              "type": "object",
              "properties": {
                "summary": {
                  "type": "string",
                  "description": "Summary of changes as conventional commit messages (max. 100 characters)."
                },
                "description": {
                  "type": "string",
                  "description": "Description of the change, in markdown format."
                },
                "version": {
                  "type": "string",
                  "enum": ["breaking", "feature", "fix"],
                  "description": "The type of version change."
                }
              },
              "required": ["summary", "description", "version"],
              "additionalProperties": false
            }

      - name: Create Pull Request
        id: create-pr
        if: steps.detect-changes.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update ${{ matrix.source.name }} API specification"
          title: ${{ fromJson(steps.release-notes.outputs.json).summary }}
          body: ${{ fromJson(steps.release-notes.outputs.json).description }}
          branch: update/${{ matrix.source.name }}
          delete-branch: true
          labels: |
            version:${{ fromJson(steps.release-notes.outputs.json).version }}
            provider:${{ matrix.source.name }}
          assignees: ${{ github.repository_owner }}

      - name: Summary
        run: |
          if [ "${{ steps.detect-first-run.outputs.first_run }}" = "true" ]; then
            echo "✅ First run completed - ${{ matrix.source.name }} API specification saved"
          elif [ "${{ steps.detect-changes.outputs.changes_detected }}" = "true" ]; then
            echo "🔄 Changes detected - Pull request created: ${{ steps.create-pr.outputs.pull-request-url }}"
          else
            echo "✅ No changes detected - ${{ matrix.source.name }} API specification is up to date"
          fi
